// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1E_fNNO8GrqsMH9puuLlR3Qi3GewOT1k',
    appId: '1:618397698961:web:203388a99b21506e6c2830',
    messagingSenderId: '618397698961',
    projectId: 'sanatan-dharmaya',
    authDomain: 'sanatan-dharmaya.firebaseapp.com',
    storageBucket: 'sanatan-dharmaya.appspot.com',
    measurementId: 'G-RFBZFF51RL',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_QQZZ2aAd8wL3VEKcm8LdYBhtEnNQdAA',
    appId: '1:618397698961:ios:fb2dd51abead463b6c2830',
    messagingSenderId: '618397698961',
    projectId: 'sanatan-dharmaya',
    storageBucket: 'sanatan-dharmaya.appspot.com',
    iosBundleId: 'com.example.sanatanDharmaya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1E_fNNO8GrqsMH9puuLlR3Qi3GewOT1k',
    appId: '1:618397698961:web:2e6fa38fcf844fcf6c2830',
    messagingSenderId: '618397698961',
    projectId: 'sanatan-dharmaya',
    authDomain: 'sanatan-dharmaya.firebaseapp.com',
    storageBucket: 'sanatan-dharmaya.appspot.com',
    measurementId: 'G-XT6DETYP7G',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_QQZZ2aAd8wL3VEKcm8LdYBhtEnNQdAA',
    appId: '1:618397698961:ios:fb2dd51abead463b6c2830',
    messagingSenderId: '618397698961',
    projectId: 'sanatan-dharmaya',
    storageBucket: 'sanatan-dharmaya.appspot.com',
    iosBundleId: 'com.example.sanatanDharmaya',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl7hPIcYwPle6Pqm1UEJxArueYg6rPXRg',
    appId: '1:618397698961:android:944de243bb8e0a256c2830',
    messagingSenderId: '618397698961',
    projectId: 'sanatan-dharmaya',
    storageBucket: 'sanatan-dharmaya.appspot.com',
  );

}